### ISSUE TITLE
wrong config in plat/kvm/Config.uk?

### ISSUE THREAD

**Issue by Air111** [unikraft/unikraft#1036]
### Describe the bug

https://github.com/unikraft/unikraft/blob/e9ad692421a373f4a9ea1b92edc1393af5507a36/plat/kvm/Config.uk
I think `KVM_KVM_KERNEL_SERIAL_CONSOLE` in line 67 means `KVM_KERNEL_SERIAL_CONSOLE` in line 38.

**Comment by michpappas** [comment]
Fixed in 4cce8306abb8191d96ce2c14c72623db934eaa6d, resolving.
