### ISSUE TITLE
README.md : Getting started section links to kraft, which is deprecated

### ISSUE THREAD

**Issue by hchandad** [unikraft/unikraft#1349]
### Describe the bug

The Getting started [section](https://github.com/unikraft/unikraft#getting-started) in the README.md, links to [kraft](https://github.com/unikraft/kraft/), which is deprecated.

### Expected behavior

Maybe point to the official getting started [document ](https://unikraft.org/docs/getting-started)or link to [kraftkit](https://github.com/unikraft/kraftkit).

**Comment by PorridgeSwim** [comment]
Hi [hchandad](https://github.com/hchandad), may I work on this issue? I'm new here and would like to start with something simple to familiarize myself with the contribution process.

**Comment by razvand** [comment]
Hi, @PorridgeSwim , sure, go ahead. It should be a simple PR. Be sure to carefully and rigorously apply the [submission checklist](https://unikraft.org/docs/contributing/unikraft).

**Comment by PorridgeSwim** [comment]
I believe this issue can be closed. I submitted a pull request to address this issue, and it has been merged: https://github.com/unikraft/unikraft/pull/1359.
