### ISSUE TITLE
Argument list too long

### ISSUE THREAD

**Issue by cffs** [unikraft/unikraft#140]
If the path to your application is a bit too deep (i.e. long) and you use libraries with a large number of object files such as musl, then some clean/build operations will fail with a message like

    make[3]: /bin/bash: Argument list too long

With musl, it happens pretty fast with `make clean`, and can also happen with `make` at the linking step, preventing build.

Changing `ARG_MAX` with `ulimit -s 65536` or larger does not help.

See [this StackOverflow question](https://stackoverflow.com/questions/64201512/argument-list-too-long-when-linking-with-gnu-make) for a discussion of the cause and possible solutions.

**Comment by cffs** [comment]
Two problems are:

1. Expansion of `CONFIG_CROSS_COMPILE` ends up giving invocations of the form `""gcc ...`. When make sees double-quotes, it passes the command to bash, triggering the over-`MAX_ARG_STRLEN` problem. One can work around it by calling make with `make CROSS_COMPILE=` which leaves just `gcc` as a linker, rather than `""gcc`.
2. When not in verbose mode, our invocation looks like `@printf ... && gcc ...`, the `&&` triggering shell invocation. You can work around it by calling make with `make V=1`.

However, even when I build with `make V=1 CROSS_COMPILE=`, make still invokes bash on the linking step although I see nothing that should trigger it in the `Makefile` expansion.

My thinking is, rather than trying to work around the problem by having make call gcc directly, and increasing `ARG_MAX` with ulimit, can't we just use **relative paths**? The root cause of the problem is that the command-line length is mostly the number of object files times the full path length. If the path was relative (and thus shorter), we would very likely stay below the limit.

**Comment by nderjung** [comment]
Closing as fixed in #619
