### ISSUE TITLE
Undefined reference to `ioctl`

### ISSUE THREAD

**Issue by nderjung** [unikraft/unikraft#195]
I'm receiving link-time errors following the merge of #153.  The following code snippet comes from our CI attempting to build NGINX:

:exclamation: **Pipeline [`nginx-staging`](https://concourse.unikraft.org/teams/apps/pipelines/nginx-staging)@[`d4c4944`](https://github.com/unikraft/app-nginx/tree/d4c494428b3d995c287d716faf56f22308b68bee) / [`compile-nginx-x86_64-kvm`](https://concourse.unikraft.org/teams/apps/pipelines/nginx-staging/jobs/compile-nginx-x86_64-kvm) on task [`build`](https://concourse.unikraft.org/builds/25654768) failed!**
```bash

   100% █████████▉ 1327/1333 [ 3.19file/s]
   100% █████████▉ 1328/1333 [ 3.99file/s]
                                          
OBJCOPY nginx_kvm-x86_64.o

   100% █████████▉ 1328/1333 [ 3.99file/s]
   100% █████████▉ 1329/1333 [ 4.00file/s]
                                          
LD      nginx_kvm-x86_64.dbg

   100% █████████▉ 1329/1333 [ 4.00file/s]/bin/ld: /tmp/build/80754af9/built/apps/nginx/build/nginx_kvm-x86_64.o: in function `tcsetattr':
/tmp/build/80754af9/built/libs/newlib/musl-imported/src/termios/tcsetattr.c:35: undefined reference to `ioctl'
/bin/ld: /tmp/build/80754af9/built/apps/nginx/build/nginx_kvm-x86_64.o: in function `tcgetattr':
/tmp/build/80754af9/built/libs/newlib/musl-imported/src/termios/tcgetattr.c:30: undefined reference to `ioctl'
/bin/ld: /tmp/build/80754af9/built/apps/nginx/build/nginx_kvm-x86_64.o: in function `ngx_spawn_process':
/tmp/build/80754af9/built/apps/nginx/build/libnginx/origin/nginx-1.15.6/src/os/unix/ngx_process.c:146: undefined reference to `ioctl'
/bin/ld: /tmp/build/80754af9/built/apps/nginx/build/nginx_kvm-x86_64.o: in function `ngx_nonblocking':
/tmp/build/80754af9/built/apps/nginx/build/libnginx/origin/nginx-1.15.6/src/os/unix/ngx_socket.c:33: undefined reference to `ioctl'
/bin/ld: /tmp/build/80754af9/built/apps/nginx/build/nginx_kvm-x86_64.o: in function `ngx_blocking':
/tmp/build/80754af9/built/apps/nginx/build/libnginx/origin/nginx-1.15.6/src/os/unix/ngx_socket.c:44: undefined reference to `ioctl'
collect2: error: ld returned 1 exit status
make[1]: *** [/tmp/build/80754af9/built/unikraft/plat/kvm/Linker.uk:24: /tmp/build/80754af9/built/apps/nginx/build/nginx_kvm-x86_64.dbg] Error 1
make: *** [Makefile:990: sub-make] Error 2

   100% █████████▉ 1330/1333 [ 2.68file/s]
                                          

```
[View in Concourse](https://concourse.unikraft.org/builds/25654768) | `fly i -b 25654768 -s build`

cc @razvand @cristian-vijelie @mogasergiu

_Issue created from a [Mattermost message](https://mattermost.nlehd.de/_redirect/pl/sn78gyfcatgn5xpopaer4kndwa) *by @nderjung*._

**Comment by nderjung** [comment]
The same issue is occurring across builds for different target applications, e.g. SQLite:

```
LD      sqlite_kvm-x86_64.dbg
   100% █████████▉ 1138/1141 [ 3.04s/file]/bin/ld: /tmp/build/80754af9/built/apps/sqlite/build/sqlite_kvm-x86_64.o: in function `tcsetattr':
/tmp/build/80754af9/built/libs/newlib/musl-imported/src/termios/tcsetattr.c:35: undefined reference to `ioctl'
/bin/ld: /tmp/build/80754af9/built/apps/sqlite/build/sqlite_kvm-x86_64.o: in function `tcgetattr':
/tmp/build/80754af9/built/libs/newlib/musl-imported/src/termios/tcgetattr.c:30: undefined reference to `ioctl'
collect2: error: ld returned 1 exit status
make[1]: *** [/tmp/build/80754af9/built/unikraft/plat/kvm/Linker.uk:24: /tmp/build/80754af9/built/apps/sqlite/build/sqlite_kvm-x86_64.dbg] Error 1
make: *** [Makefile:990: sub-make] Error 2
   100% █████████▉ 1139/1141 [ 2.44s/file]
                                          
```
[View in Concourse](https://concourse.unikraft.org/builds/25654749) | `fly i -b 25654749 -s build`

**Comment by mogasergiu** [comment]
I believe the problem is that those applications may need to have:
```#define UK_LIBC_SYSCALL (1)```
specified at the very beginning in order to make the call through the libc-style wrapper (or call it through ```uk_syscall(SYS_ioctl,...)```), since ```ioctl``` was registered using ```UK_LLSYSCALL_R_DEFINE``` because the libc-style wrapper doesn't match the signature and return type of the underlying syscall.

Thus, the issue seems to be solved by adding the previously mentioned ```#define UK_LIBC_SYSCALL (1)``` at the very beginning of ```main.c``` from ```nginx```. Otherwise, the calls to ```ioctl()``` should be changed to ```uk_syscall(SYS_ioctl, ...)``` to eliminate the issue.

**Comment by skuenzer** [comment]
Hum... :thinking: This is compiled against musl, right? I am rather expecting (I did not check if this is the case) that musl is currently not compiling the `ioctl` wrapper. Normally, `musl` is providing all libc-wrappers and calls the actual Unikraft implementation through the our syscall shim. Because we were still registering some syscalls, we switched some wrappers off in musl's `Makefile.uk`.
In general, we should never touch `UK_LIBC_SYSCALL` with application code, it is the responsibility by the libc's to configure this accordingly. For instance,`nolibc` sets it since it does not provide any libc syscall wrappers but `musl` provides its own wrappers so the option should be off.

**Comment by nderjung** [comment]
Any progress on this?

**Comment by justin-he** [comment]
> 
> 
> I believe the problem is that those applications may need to have:
> `#define UK_LIBC_SYSCALL (1)`
> specified at the very beginning in order to make the call through the libc-style wrapper (or call it through `uk_syscall(SYS_ioctl,...)`), since `ioctl` was registered using `UK_LLSYSCALL_R_DEFINE` because the libc-style wrapper doesn't match the signature and return type of the underlying syscall.
> 
> Thus, the issue seems to be solved by adding the previously mentioned `#define UK_LIBC_SYSCALL (1)` at the very beginning of `main.c` from `nginx`. Otherwise, the calls to `ioctl()` should be changed to `uk_syscall(SYS_ioctl, ...)` to eliminate the issue.

Hi, could you please share the workaround here in patch format? Thanks. I met the same issue when testing nginx on Arm kvm plat

**Comment by justin-he** [comment]
Hi all, please try this patch:
```
diff --git a/lib/vfscore/main.c b/lib/vfscore/main.c
index 11bfa93..0ecad74 100644
--- a/lib/vfscore/main.c
+++ b/lib/vfscore/main.c
@@ -673,7 +673,7 @@ out_errno:
        return -error;
 }
 
-#if UK_LIBC_SYSCALL
+#if UK_LIBC_SYSCALLS
 int ioctl(int fd, unsigned long int request, ...)
 {
        va_list ap;
```

**Comment by nderjung** [comment]
@justin-he this works for  me
