### ISSUE TITLE
Multiple definition of `time` when using `newlib` with `uktime`

### ISSUE THREAD

**Issue by craciunoiuc** [unikraft/unikraft#198]
Since this commit 00ca344fcb38b7ab089a1cb4f2c1379e16706d83 introduced by this [Pull Request](https://github.com/unikraft/unikraft/pull/124) building any application that uses `newlib` and `uktime` will fail.

I encountered this while compiling the `helloworld` application with `lwip`, `pthread-embedded` and `newlib`. The message printed:
```
100% █████████▉ 1327/1333 [ 2.93file/s]/bin/ld: /tmp/build/80754af9/built/apps/nginx/build/libnewlibc.o: in function `time':
/tmp/build/80754af9/built/apps/nginx/build/libnewlibc/origin/newlib-2.5.0.20170922/newlib/libc/time/time.c:43: multiple definition of `time'; /tmp/build/80754af9/built/apps/nginx/build/libuktime.o:/tmp/build/80754af9/built/unikraft/lib/uktime/time.c:126: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [/tmp/build/80754af9/built/unikraft/plat/kvm/Linker.uk:22: /tmp/build/80754af9/built/apps/nginx/build/nginx_kvm-x86_64.dbg] Error 1
make: *** [Makefile:990: sub-make] Error 2
```
(This was taken from [Mattermost](https://mattermost.nlehd.de/uk-community/pl/agybfcpwyf84xr9nha43g8e5wo))

As the error states, there are multiple definitions of the `time` function. The `time` function from `lib/uktime/time.c` should not be used if the one from `newlib` is available.

**Comment by skuenzer** [comment]
I rather think we should either consider not to build the `time` function with newlib or to exclude `uktime` from the build configuration when newlib is used.

**Comment by nderjung** [comment]
@skuenzer, the former is the "easier" solve.  Removing `uktime` is a bit tricker (e.g. replacing instances of `select LIBUKTIME` with `select LIBUKTIME if !HAVE_LIBC`) since, newlib, posix-process, vfscore, kvm, xen and at least nginx is dependent on it.

**Comment by razvand** [comment]
@nderjung , @craciunoiuc , @skuenzer , this is solved here: https://github.com/unikraft/lib-newlib/pull/5

**Comment by razvand** [comment]
I will close this issue, as [the solving PR](https://github.com/unikraft/lib-newlib/pull/5) has been merged.
