### ISSUE TITLE
[RFC] Implement the smp boot on Arm64 kvm plat

### ISSUE THREAD

**Issue by justin-he** [unikraft/unikraft#253]
To support smp in Unikraft, smp boot is the preparatory work. On Arm64 kvm plat, psci call should be used to boot vcpus.

**Comment by justin-he** [comment]
I have finished the rebasing to latest branch. But this patch series depends on my virtio-mmio and pci-ecam series. I will wait for a while to reduce the backporting work

**Comment by marcrittinghaus** [comment]
SMP for ARM64 and X86 has been implemented.
