### ISSUE TITLE
remove __i386__ code

### ISSUE THREAD

**Issue by felipehuici** [unikraft/unikraft#26]
We are never going to support 32-bit on x86, but we have "#ifdef i386" all over the place, which hurts readability. Also many files will shrink dramatically

**Comment by mprey** [comment]
Hello, we are students at The University of Texas at Austin. We are planning on trying our hand at this issue, do you have any pointers for us before we start?

Thanks.

**Comment by hisharanwithu** [comment]
Hello @mprey, 
I am Sharan. The primary purpose of this issue is to remove some of the redudant i386 arch specific code from the xen platform ```./plat/xen```. On completion of this task, we must ensure that the xen platform still work on x86_64 arch.
