### ISSUE TITLE
remove code under #ifndef CONFIG_PARAVIRT

### ISSUE THREAD

**Issue by felipehuici** [unikraft/unikraft#27]
We inherited bits of PVH code from Minios. The problem is this code did not work even for Minios. There is little point in keeping these bits. However it might be good to keep the -DCONFIG_PARAVIRT, as hints for future

**Comment by jenchen18** [comment]
Hi, I'm a student taking a virtualization class at UT Austin, and I'm currently collaborating with one other. @felipehuici Is it possible that we can get more information about this issue if it's still available?

**Comment by marcrittinghaus** [comment]
Issue solved with aforementioned PRs.
