### ISSUE TITLE
Reintroduce original vfscore as ukfdtab

### ISSUE THREAD

**Issue by felipehuici** [unikraft/unikraft#32]
The original VFScore implementation was implementing jsut a file descriptor lookup table providing basic callbacks for read/write/... etc. If we do not need any real filesystem, just a few sockets and maybe unnamed pipes, this implementation is good enough for those unikernels and much more specialized. The idea would be to provide ukfdtab as vfscore alternative and maybe introduce macros that map to particular fd creation functionalities depending on which one of the libs is chosen. This way we can keep a single implementation for file descriptor openers provides by other libraries (e.g., socket(), ...).

**Comment by skuenzer** [comment]
Hum, I guess by mistake, there was a new issue opened that addresses this: https://github.com/unikraft/unikraft/issues/52
