### ISSUE TITLE
`uk/bus.h`: No such file or directory

### ISSUE THREAD

**Issue by nderjung** [unikraft/unikraft#325]
### Describe the bug

Missing header `uk/bus.h` in arm64 builds in `plat/drivers/virtio/virtio_bus.c`.

### Steps to reproduce

Built standard helloworld for arm64 and kvm.

### Which architectures were you using or does this bug affect?

arm64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
/tmp/build/80754af9/built/unikraft/plat/kvm/arm/lcpu.c: In function 'ukplat_lcpu_halt_irq':
/tmp/build/80754af9/built/unikraft/plat/kvm/arm/lcpu.c:49:2: warning: implicit declaration of function 'halt' [-Wimplicit-function-declaration]
   49 |  halt();
      |  ^~~~
/tmp/build/80754af9/built/unikraft/plat/drivers/virtio/virtio_bus.c:37:10: fatal error: uk/bus.h: No such file or directory
   37 | #include <uk/bus.h>
      |          ^~~~~~~~~~
```

**Comment by rene** [comment]
@nderjung , I couldn't reproduce this issue with master version. I think this bug is not valid anymore, am I right? In case you can still reproduce, please, share your config file here.

**Comment by nderjung** [comment]
I can no longer reproduce the issue and also thanks for checking @rene.  I'll close the issue.
