### ISSUE TITLE
Unreliable TSC causes underflow

### ISSUE THREAD

**Issue by jschlumpp** [unikraft/unikraft#334]
### Describe the bug

Currently, Unikraft relies on the x86 timestamp counter to retrieve the current time. On some platforms the counters are not perfectly synchronized and therefore `rdtsc` can return non-monotonically increasing values after a core migration.
This results in an underflow in [`tscclock_monotonic`](https://github.com/unikraft/unikraft/blob/7d6707f337c24f23fd6f0350430f915a3371d329/plat/kvm/x86/tscclock.c#L207), which causes more issues such as breaking the timeout for `select` (The large unsigned value of `tscclock_monotonic` overflows when casted to a signed type, resulting in a negative wake up time). 

Other software projects such as [rust](https://github.com/rust-lang/rust/blob/62efba8a050c64249dab942951bb28f710208bc8/library/std/src/time.rs#L247-L285) also faced this issue before and implemented [workarounds](https://github.com/rust-lang/rust/blob/62efba8a050c64249dab942951bb28f710208bc8/library/std/src/time/monotonic.rs). 

### Steps to reproduce

This was observed during testing app-nginx application in release mode (the debug build seems to be slow enough, so that the issue does not occur).
The following processors were tested so far:

- AMD Ryzen 3900X: broken
- AMD Ryzen 5850U: broken
- Intel 4770T: works
- AWS EC2 C5N Xeon Platinum 8124M (two sockets): broken

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

**Comment by orangeadam3** [comment]
Hi, my name is Adam, I'm currently taking the virtualization class at the University of Texas at Austin. I'd would like to make a pull request for this bug along with #16 & #89.  Once I do the pull request i would submit my patches like described in CONTRIBUTING.md. Is this ok by you.

**Comment by razvand** [comment]
Hi, @orangeadam3 . Sure, you can go ahead and work on these PRs.

Also, any PR you create that fixes warning in the build process of [Unikraft applications](https://github.com/search?q=topic%3Aunikraft-application+org%3Aunikraft+fork%3Atrue) is welcome. This is to give you a more "getting accustomed to Unikraft and its build process" type of tasks.
