### ISSUE TITLE
error: unrecognized command line option `-mstack-protector-guard=global`

### ISSUE THREAD

**Issue by nderjung** [unikraft/unikraft#351]
### Describe the bug

Attempting to compile [helloworld](https://github.com/unikraft/app-helloworld) for ARM as Linux Userspace application results in a compile-time error.

### Steps to reproduce

 * `CONFIG_ARCH_ARM_32=y`
 * `CONFIG_PLAT_LINUXU=y`
 * `CONFIG_LIBPOSIX_LIBDL=y`
 * `CONFIG_LIBPOSIX_PROCESS=y`
 * `CONFIG_LIBPOSIX_USER=y`
 * `CONFIG_LIBPOSIX_SYSINFO=y`
 * `CONFIG_LIBVFSCORE=y`
 * `CONFIG_LIBUKSWRAND=y`
 * `CONFIG_LIBUKSP=y`
 * `CONFIG_LIBUKBLKDEV=y`
 * `CONFIG_LIBSYSCALL_SHIM=y`

### Which architectures were you using or does this bug affect?

arm

### Which platforms were you using or does this bug affect?

linuxu

### Relevant log output

```shell
AS      liblinuxuplat: entry32.o
arm-linux-gnueabihf-gcc: error: unrecognized command line option '-mstack-protector-guard=global'; did you mean '-fstack-protector-all'?
make[1]: *** [/tmp/build/80754af9/built/unikraft/support/build/Makefile.build:50: /tmp/build/80754af9/built/apps/helloworld/build/liblinuxuplat/entry32.o] Error 1
make: *** [Makefile:1015: sub-make] Error 2
make: Leaving directory '/tmp/build/80754af9/built/unikraft'
```

**Comment by skuenzer** [comment]
Hum 🤔 , these flags are set by `lib/uksp` (you set `CONFIG_LIBUKSP=y`). Probably we need an update here for arm32? Could it be that it depends on the compiler version?

**Comment by nderjung** [comment]
We set `uksp` in the CI.  I'm not sure if it depends on the compiler, which is compiled with these options defined [here](https://github.com/unikraft/kraft/blob/staging/package/docker/Dockerfile.gcc#L102-L132).

cc'ing @unikraft/sig-arch-arm

**Comment by michpappas** [comment]
Hi @nderjung, GCC does not support mstack-protector-global in 32-bit Arm. See:

* https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/ARM-Options.html#ARM-Options
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102352

Opened #382 with fix
