### ISSUE TITLE
Django on Unikraft

### ISSUE THREAD

**Issue by felipehuici** [unikraft/unikraft#40]
Unikraft supports Pyhonv3, and the Django packages can be installed via pip. Right now the port crashes because we don't have an implementation of socketpair(), though after fixing this other issues may arise. This project consists of going through these, with the aim of having Django run on Unikraft.

**Comment by snemana232** [comment]
I'm an undergraduate at the University of Texas at Austin, and am interested in this issue for a project in my virtualization class. Could you tell me more about this issue?

**Comment by razvand** [comment]
Hi, @snemana232 . We want to port the [Django framework](https://www.djangoproject.com/) on Unikraft, given the [Python 3 support](https://github.com/unikraft/lib-python3). You should aim to first build the [app-python3](https://github.com/unikraft/app-python3/) application then aim to build Django with Unikraft and see what are the issues, such as the lack of the `socketpair()` call. And start fixing those.

We can talk more on [Discord](https://bit.ly/UnikraftDiscord), on the `python3` text channel.

**Comment by vladandrew** [comment]
I also recommend the Unikraft Summer School resources[1] to get you started.

[1] https://usoc21.unikraft.org/docs/
