### ISSUE TITLE
probably a bug in uk_posix_memalign_ifpages

### ISSUE THREAD

**Issue by sartakov** [unikraft/unikraft#49]
Hi 

I am using `uk_posix_memalign_ifpages` to allocate memory for a stack and get, let's say,  0x7fb2ae400000. 
the corresponding metadata is stored at 0x7fb2ae3ff000 (a previous page, as it stated in alloc.c). 
I look inside this structure and see that the allocation starts from 0x7fb2ae000000 and includes 801 pages. I am trying to figure out how the number 801 appears and don't understand. I think it should be 800, because the metadata page is a part of the padding.

I thought the function always returns one additional page, but, when I use it to allocate a smaller memory region, let's say 0x1008 bytes aligned at 8, I receive something like: 

return =  0x7fb2ac018010,  metadata= 0x7fb2ac018000, metadada.begin = 0x7fb2ac018000 metadata.num_pages = 2. This result is correct, and the metadata page is included into the range.

**Comment by nderjung** [comment]
\cc @hlef

**Comment by hlef** [comment]
Hi @sartakov, thanks for this bug report.

I already have a patch for this but did not send it for review yet. This will be fixed soon.
