### ISSUE TITLE
syscall clock_getres not implemented

### ISSUE THREAD

**Issue by StefanJum** [unikraft/unikraft#496]
### Describe the bug

The `clock_getres`system call is not implemented, at the moment it [just returns 0](https://github.com/unikraft/unikraft/blob/staging/lib/uktime/time.c#L142).
This becomes an issue with binary compatibility since it is used by some run-time environments.
For example, the dlang helloworld app crashes because it does a division by the number of nanoseconds returned by `clock_getres` in the (struct timespec *res) parameter (see the #495 issue for more detailed information).

**Comment by marcrittinghaus** [comment]
Solved with PR #503
