### ISSUE TITLE
CNCF TAG-Runtime Discussion/Presentation (?)

### ISSUE THREAD

**Issue by raravena80** [unikraft/unikraft#521]
### Describe the bug

Hello Unikraft team,

Opening as a follow up to [this](https://github.com/unikraft/unikraft/discussions/511) to try to get more visibility. 

I'm one of the co-chairs of the CNCF TAG-Runtime. I believe you had an agenda item to present the project in our meeting. I'm following up, I think it would be great for you to present/discuss the project in the future.

Feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com) at your convenience. 

Thanks!

### Steps to reproduce

N/A

### Expected behavior

N/A

**Comment by nderjung** [comment]
Hi @raravena80, apologies, with a release around the corner (tomorrow || early saturday morning) and a few less hands on-deck over August, we only caught this now.  I'll move the discussion back to the GH discussions tab if that's ok. Thanks! :)
