### ISSUE TITLE
Unable to build apps on x86 with clang due to nested macros limitation

### ISSUE THREAD

**Issue by mariasfiraiala** [unikraft/unikraft#532]
### Describe the bug

When trying to use `clang` as a compiler with `x86` apps, the building process fails due to `clang` having a nested macros limit of 20.

The output provided by the compiler suggests to increase this limit by using the `-asm-macro-max-nesting-depth` flag. 

### Steps to reproduce

Configure your app in your prefered manner and build it using:
```
make CC=clang
```

### Expected behavior

I expected the building stage to be successfully completed, even when using `clang`.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
<instantiation>:14:11: error: macros cannot be nested more than 20 levels deep. Use -asm-macro-max-nesting-depth to increase this limit.
 pte_fill ((((((((((((((((((((0x00000000c0000000 + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1 << (12 + (9 * 1))) * 8) + (1UL << (12 + (9 * 1))) * 8), ((((((((((((((((((((0x200 - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8) - 8), 1, (0x001UL | 0x002UL)
```

**Comment by marcrittinghaus** [comment]
Hi @mariasfiraiala,

thanks for pointing this out. Have you tested to use the flag?

**Comment by mariasfiraiala** [comment]
Yes, I did.
@vladandrew suggested that I include this
```
ASFLAGS-$(call have_clang)     += -mllvm -asm-macro-max-nesting-depth=1000
```
in `Makefile.uk` and it works fine.

Waiting for a PR from him with this fix.
