### ISSUE TITLE
libc Test Library

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#538]
### Feature request summary

Add Unikraft library to test libc variants ([Musl](https://github.com/unikraft/lib-musl), [newlib](https://github.com/unikraft/lib-newlib), [nolibc](https://github.com/unikraft/unikraft/tree/staging/lib/nolibc)). The library will ensure proper functionality provided by libc variants. The starting point is [libc-test](https://wiki.musl-libc.org/libc-test.html).

### Describe alternatives

[uktest](https://github.com/unikraft/unikraft/tree/staging/lib/uktest) could be used for unit testing of Unikraft components. However, the better approach is porting an existing and well maintained [libc test library](https://wiki.musl-libc.org/libc-test.html) that eventually makes use of [uktest](https://github.com/unikraft/unikraft/tree/staging/lib/uktest).

**Comment by nderjung** [comment]
Closing as rendered: https://github.com/unikraft/lib-libc-test
