### ISSUE TITLE
Re-order lib/Makefile.uk?

### ISSUE THREAD

**Issue by nderjung** [unikraft/unikraft#55]
Should this list be alphabetical?

**Comment by skuenzer** [comment]
I am not sure if the order in this file matters much. Sharan changed KConfig to order the items in `menuconfig`. This is not visible.

**Comment by aadhi0319** [comment]
Hello! I'm an undergraduate at the University of Texas at Austin. We have a project where we need to contribute to a virtualizatino repository of our choice. Unikraft was very interesting to our group and we would like to contribute to it. I've cloned the repo and it seems like I would just have to reorder the directories in `lib/Makefile.uk` to be in alphabetical order . Would this be a good first issue to work on? Thank you!

**Comment by nderjung** [comment]
Hey @aadhi0319,

Thanks for your interest in Unikraft!  If you are using this to practice contributing to the Unikraft project, then please do submit a PR with this change to learn about the process.  If it passes the CI then it this should be feasible to merge; as @skuenzer suggested, the ordering (probably, let the CI/CD tell us for certain) doesn't really matter so much in terms of KConfig's ability to parse and process these files.  For me, the suggestion/issue comes as a result of just wanting to be able to read the source file quickly to check if a lib is indeed included whilst hacking/adding internal libraries.

**Comment by aadhi0319** [comment]
@nderjung 
Thank you for the quick reply. I will get that pull request in soon. We plan to do "harder" issues too, but we were told by our professor to start off with an "easy" issue to get familiar with the open source process.

**Comment by razvand** [comment]
@aadhi0319 , please join us on [Discord](https://bit.ly/UnikraftDiscord) where he have community discussions and host meetings and hackathons. That will get you a chance to interact with the community and get a hold of ideas and projects in the community.

**Comment by aadhi0319** [comment]
@razvand Thank you for the invite! @nderjung I just submitted a pull request, but I'm not sure how to link it to this issue.

**Comment by nderjung** [comment]
Rendered #332.
