### ISSUE TITLE
Xen Project and Unikraft.

### ISSUE THREAD

**Issue by hack3rcon** [unikraft/unikraft#56]
Hello Unikraft team,
The Xen Project is in the frontline of the Unikernel projects, but why the team working on the KVM? I can remember that the Unikraft introduced by Xen Project!
Please improve Xen supporting.

Thanks.

**Comment by nderjung** [comment]
What features are lacking?

To address your concern, Unikraft does support the Xen hypervisor and more features, greater support, etc. are actively being developed.  Unikraft is also a Linux Foundation project, and so support for KVM is also intrinsic to the project.

If you would like to contribute to Unikraft, to increase support for Xen (which ever those features you see as lacking), please read our [`CONTRIBUTING.md`](https://github.com/unikraft/unikraft/tree/staging/CONTRIBUTING.md) guidelines for getting started.
