### ISSUE TITLE
Rust Support

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#578]
### Feature request summary

Add Rust support for external libraries / applications.
Applications written in Rust to be built on top of Unikraft.

**Comment by razvand** [comment]
I think this can be closed with the introduction of https://github.com/unikraft/kraftkit/pull/703 and https://github.com/unikraft/unikraft/pull/957

@mkroening , could you confirm?

**Comment by sanmai-NL** [comment]
@razvand One issue reference is duplicate.

**Comment by mkroening** [comment]
Yes, this was resolved by

- https://github.com/rust-lang/rust/pull/113411
- https://github.com/unikraft/kraftkit/pull/703
- https://github.com/unikraft/catalog/pull/16
