### ISSUE TITLE
Xen arm64 (aarch64) support

### ISSUE THREAD

**Issue by skuenzer** [unikraft/unikraft#62]

**Comment by alexpclarke** [comment]
Is Xen on arm64 host a feature that is currently in development? I would like to use this pairing but I do not see a way to achieve it yet. If not, what would you suggest is the best way to get a unikernel working on a Raspberry Pi 4b? I am doing this as an introduction to unikernels and would like to use unikraft if possible.

**Comment by vladandrew** [comment]
Hi Alex, I'm not sure if anyone is working on this issue. Regarding raspberry pi support, there has been some work into this, there are several patches on patchwork, but for the 3 b+[1]. Sadly they are a kind of old. 

[1] https://patchwork.unikraft.org/project/unikraft/list/?series=1161

**Comment by razvand** [comment]
Hi, @alexpclarke . There is no progress on the Xen on arm64 support. There is progress, however, on adding arm64 features in Unikraft (#206 , #208 , #231 ). @razvanvirtan , could you elaborate on this? What is the physical device (with arm64) that you are using for development?

@skuenzer , could you provide @alexpclarke with some updates on the R-Pi support?

**Comment by razvanvirtan** [comment]
Sure, I am currently using a Qualcomm Falkor for physical tests. As about the PRs, #208 provides networking support on arm64 unikraft (it also needs the changes in #206 to work with the staging version).

**Comment by oleksiimoisieiev** [comment]
Posted MR https://github.com/unikraft/unikraft/pull/726 which adds XEN arm64 support.

**Comment by razvand** [comment]
Fixed by #726
