### ISSUE TITLE
posix-futex: Buiding tests fails on newer scheduling API

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#630]
### Describe the bug

Changes in the scheduling API, as part of PR #564 cause the build process of [`posix-futex` tests](https://github.com/unikraft/unikraft/blob/staging/lib/posix-futex/tests/test_posix_futex.c) to fail. They are using the old style `uk_thread_create()` function. The newer API uses `uk_sched_thread_create()`.

### Steps to reproduce

Use the [`do-helloworld` Musl test script](https://github.com/unikraft-upb/scripts/tree/main/musl#app-helloworld). After running:

```
./do-helloworld build
```

enter the `workdir/apps/app-helloworld/` directory, run

```
export UK_WORKDIR=$(pwd)/../..
kraft menuconfig
````

and enable `uktest` and tests for `posix-futex`. Then get back to the top-level directory and run again

```
./do-helloworld build
```

This is when the build fails.

### Expected behavior

There shouldn't be a build / link error.

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
/home/razvan/projects/unikraft/scripts/musl/workdir/apps/app-helloworld/build/helloworld_kvm-x86_64.o: In function `_uk_testsuite_posix_futex_testsuite_case_test_cmp_requeue_two_waite
rs_one_waker':                                                                                                                                                                         
/home/razvan/projects/unikraft/scripts/musl/workdir/unikraft/lib/posix-futex/tests/test_posix_futex.c:393: undefined reference to `uk_thread_create'                                   
/home/razvan/projects/unikraft/scripts/musl/workdir/unikraft/lib/posix-futex/tests/test_posix_futex.c:394: undefined reference to `uk_thread_create'                                   
/home/razvan/projects/unikraft/scripts/musl/workdir/unikraft/lib/posix-futex/tests/test_posix_futex.c:395: undefined reference to `uk_thread_create'                                   
/home/razvan/projects/unikraft/scripts/musl/workdir/unikraft/lib/posix-futex/tests/test_posix_futex.c:397: undefined reference to `uk_thread_wait'                                     
/home/razvan/projects/unikraft/scripts/musl/workdir/unikraft/lib/posix-futex/tests/test_posix_futex.c:402: undefined reference to `uk_thread_create'
```

**Comment by noureddine-taleb** [comment]
I will work on that.
