### ISSUE TITLE
uksched: Interrupt during booting process causes switch to idle thread which gets stuck

### ISSUE THREAD

**Issue by mariasfiraiala** [unikraft/unikraft#643]
### Describe the bug

Functions from the `__wq_wait_event_deadline` macro (defined in [`lib/uksched/include/uk/wait.h`](https://github.com/unikraft/unikraft/blob/staging/lib/uksched/include/uk/wait.h#L96)) are heavily influenced by the presence or absence of interrupts.

The problem lies in what might happen between lines [116](https://github.com/unikraft/unikraft/blob/staging/lib/uksched/include/uk/wait.h#L116) and [119](https://github.com/unikraft/unikraft/blob/staging/lib/uksched/include/uk/wait.h#L119). Starting with line 116, interrupts are enabled. If there is an interrupt fired before the `yield` call at line 119, the IRQ handler `_ukplat_irq_handler()` kicks the scheduler out of the halting loop by clearing the `sched_have_pending_events` bit, which marks that no more work is left to be done. 

This is a problem when `yield()` is invoked in the early process of starting the unikernel (for boot threads, `init` and `idle`). Control is passed to the `idle` thread after the `yield()` call and due to the `sched_have_pending_events` bit being 0, the scheduler never passes control back to the `init` thread which does all the work.

This is how execution stops and gets stuck at certain points in the boot process when an interrupt fires right before the `yield()` call. It happens on both `redis` and `SQLite`, right after mounting the `9pfs` filesystem or other I/O operations.

The problem resurfaces now, with current work being done on refactoring the scheduling API and replacing `newlib` with `musl`.

### Steps to reproduce

Use an app that relies on "multithreading", `redis` or `SQLite`, with the new scheduling API.

### Expected behavior

I expected the unikernel to not get stuck during early boot stages.

### Which architectures were you using or does this bug affect?

arm64

### Which platforms were you using or does this bug affect?

kvm

**Comment by eduardvintila** [comment]
This problem actually surfaces on all applications which eventually, either directly or indirectly, use `uk_sched_yield()` to switch control to another thread. 

If an interrupt fires during the context switch, the interrupted thread seems to never be placed back on the CPU by the scheduler ever again. 

The `run_queue` of the `schedcoop` scheduler, for example, does not seem to include this thread at all when this phenomenon occurs, causing the scheduler to switch back and forth only between the rest of the threads, which might not do much work at all.

In particular, the `python3` app uses 4 threads throughout the booting process: `init` (the main thread which does most of the work), `idle`, `netdev` and `lwip`. If the `init` thread is interrupted during a context switch, it seems that it's not added to the `run_queue` and therefore will never be scheduled again on the CPU. This means that the scheduler has no choice but to choose between the last three threads which don't actually advance the booting process and therefore the application will get completely stuck.

**Comment by marcrittinghaus** [comment]
This seems to be a pretty serious bug, which should be fixed before the release. Any suggestions on that? Is someone working on finding a solution?

**Comment by eduardvintila** [comment]
> This seems to be a pretty serious bug, which should be fixed before the release. Any suggestions on that? Is someone working on finding a solution?

Hi, @marcrittinghaus. Me and @mariasfiraiala are currently investigating this and will try to come up with a proper solution soon.

**Comment by mariasfiraiala** [comment]
> This seems to be a pretty serious bug, which should be fixed before the release. Any suggestions on that? Is someone working on finding a solution?

@marcrittinghaus Finding a solution may take a while. Due to the tight schedule and the release coming so soon, I doubt we'll have something satisfactory by then.

**Comment by marcrittinghaus** [comment]
@eduardvintila @mariasfiraiala thanks for looking into this 🙏🏻 If it does not make it into the release, we upstream the fix hopefully soon afterwards. Although I guess due to the massive changes there will be a lot of bug fixes coming.

**Comment by jschlumpp** [comment]
I wrote a short quick-and-dirty [patch](https://gist.github.com/mschlumpp/a73c11ccf592cde6fc053ca8e455b809) for the race condition I found.
> If an interrupt fires during the context switch, the interrupted thread seems to never be placed back on the CPU by the scheduler ever again.

However, I'm not sure whether there are other race-conditions...

**Comment by eduardvintila** [comment]
> 



> I wrote a short quick-and-dirty [patch](https://gist.github.com/mschlumpp/a73c11ccf592cde6fc053ca8e455b809) for the race condition I found.
> 
> 
> However, I'm not sure whether there are other race-conditions...

Hi, @mschlumpp! Nice find! The patch looks good, but unfortunately does not cover the race condition mentioned in this issue (I've tested the patch with `app-python3`). Our race-condition happens, I think, right before finishing the `yield()` to the `idle` thread. Once `idle` gets control, it seems that the scheduler never switches back to the `init` thread, since it cannot find it in the `run_queue` list.

**Comment by mariasfiraiala** [comment]
> I wrote a short quick-and-dirty [patch](https://gist.github.com/mschlumpp/a73c11ccf592cde6fc053ca8e455b809) for the race condition I found.

@mschlumpp Since this patch seems to be fixing another race condition, would it make sense to provide a PR with it? Together with #694 we'd have all the current race conditions covered and we'll be sure that there won't be any other problems popping up.
