### ISSUE TITLE
Add code quality status badge to `README.md`

### ISSUE THREAD

**Issue by nderjung** [unikraft/unikraft#650]
### Feature request summary

This issue tracks the addition of a code quality badge to the main `README.md`.

```
[![Codacy Badge](https://app.codacy.com/project/badge/Grade/454f62251d96413fac8024b28df2ce5b)](https://www.codacy.com/gh/unikraft/unikraft/dashboard?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=unikraft/unikraft&amp;utm_campaign=Badge_Grade)
```

Will result in:

[![Codacy Badge](https://app.codacy.com/project/badge/Grade/454f62251d96413fac8024b28df2ce5b)](https://www.codacy.com/gh/unikraft/unikraft/dashboard?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=unikraft/unikraft&amp;utm_campaign=Badge_Grade)

**Comment by kiranchandrasekhar** [comment]
Hello, I am representing a group of undergraduate UT Austin students aiming to contribute to open-source virtualization projects on behalf of a virtualization course. Could we have this issue assigned to us?
