### ISSUE TITLE
Integrate patches for initial ramdisk support

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#68]
These are patches initially sent by Robert Hrusecky: https://patchwork.unikraft.org/cover/737071/
https://lists.xenproject.org/archives/html/minios-devel/2020-01/msg00209.html

Update them to the current Unikraft version, submit them for review and ensure they are upstreamed.

**Comment by razvand** [comment]
New submission: https://patchwork.unikraft.org/patch/738173/
https://lists.xenproject.org/archives/html/minios-devel/2020-11/msg00056.html

**Comment by vladandrew** [comment]
I've reopened this issue since the patches have not been upstreamed. I was trying to run nginx but couldn't since these patches were not upstreamed.
