### ISSUE TITLE
build: Wrongly ordered libraries make compilation fail

### ISSUE THREAD

**Issue by mkroening** [unikraft/unikraft#717]
Originally opened as
 - https://github.com/unikraft/kraftkit/issues/186

The given `Kraftfile` sometimes succeeds in building; sometimes it fails.

I found the issue to be the order of include directories in `build/libposix_socket/driver.o.cmd`.

[good_driver.o.cmd](https://github.com/unikraft/unikraft/files/10426687/good.txt)
[bad_driver.o.cmd](https://github.com/unikraft/unikraft/files/10426688/bad.txt)

Sometimes, `good_driver.o.cmd` is generated, but sometimes `bad_driver.o.cmd` is generated. This is hard to reproduce, though.

```diff
--- good_driver.o.cmd     2023-01-16 14:34:19.898251055 +0000
+++ bad_driver.o.cmd      2023-01-16 14:34:22.431743728 +0000
@@ -57,6 +57,9 @@
     -I/root/pwd/kraftkit-foo/.unikraft/unikraft/lib/ukswrand/include \
     -I/root/pwd/kraftkit-foo/.unikraft/unikraft/lib/uktimeconv/include \
     -I/root/pwd/kraftkit-foo/.unikraft/unikraft/lib/vfscore/include \
+    -I/root/pwd/kraftkit-foo/.unikraft/libs/lwip/include \
+    -I/root/pwd/kraftkit-foo/.unikraft/libs/lwip/musl-imported/include \
+    -I/root/pwd/kraftkit-foo/build/liblwip/origin/fork-lwip-UNIKRAFT-2_1_x/src/include \
     -I/root/pwd/kraftkit-foo/build/libmusl/origin/musl-1.1.19//arch/x86_64 \
     -I/root/pwd/kraftkit-foo/build/libmusl/origin/musl-1.1.19//arch/generic \
     -I/root/pwd/kraftkit-foo/.unikraft/libs/musl/include \
@@ -103,9 +106,6 @@
     -I/root/pwd/kraftkit-foo/build/libmusl/include/setjmp/include \
     -I/root/pwd/kraftkit-foo/build/libmusl/include/locale/include \
     -I/root/pwd/kraftkit-foo/build/libmusl/include/complex/include \
-    -I/root/pwd/kraftkit-foo/.unikraft/libs/lwip/include \
-    -I/root/pwd/kraftkit-foo/.unikraft/libs/lwip/musl-imported/include \
-    -I/root/pwd/kraftkit-foo/build/liblwip/origin/fork-lwip-UNIKRAFT-2_1_x/src/include \
     -D__X86_64__ \
     -m64 \
     -mno-red-zone \
```

Running `good_driver.o.cmd` on the described setup succeeds.
`bad_driver.o.cmd` results in the issue:

```bash
[..]
/root/pwd/kraftkit-foo/.unikraft/unikraft/lib/posix-socket/include/uk/socket_driver.h: At top level:
/root/pwd/kraftkit-foo/.unikraft/unikraft/lib/posix-socket/include/uk/socket_driver.h:529:7: error: unknown type name 'socklen_t'; did you mean 'locale_t'?
  529 |       socklen_t addrlen)
      |       ^~~~~~~~~
      |       locale_t
cc1: note: unrecognized command-line option '-Wno-array-parameter' may have been intended to silence earlier diagnostics
```

**Comment by mkroening** [comment]
Closing in favor of https://github.com/unikraft/kraftkit/issues/186.

**Comment by mkroening** [comment]
Just to recap: KraftKit does not order libraries and passes them in a random order to make: `make L=musl L=lwip`.

Unikraft's build system is sensitive to this order, as it directly translates to the include-directory order. This might break compilation, e.g. when lwip comes before musl in my case.

@nderjung suggests that correctly ordering libraries is the responsibility of the Unikraft build system: https://github.com/unikraft/kraftkit/issues/186#issuecomment-1386804211

**Comment by mkroening** [comment]
A useful resource by @mschlumpp: [trofi's blog: New make --shuffle mode](https://trofi.github.io/posts/238-new-make-shuffle-mode.html)

**Comment by jschlumpp** [comment]
I think the "low-level" Unikraft Makefiles shouldn't be responsible for this. The problem is that the libraries would have to specify their dependencies somewhere. And I think that is more of a "high-level" kraftkit issue. 

But if we still want to tackle this as part of the core Unikraft build system, we may use something like [tsort](https://www.gnu.org/software/coreutils/manual/html_node/tsort-invocation.html#tsort-invocation) to generate a sorted list based on the dependencies.

**Comment by nderjung** [comment]
cc'ing @skuenzer who knows more about this. From a conversation (albeit a while back) it seemed like an issue that the makefile-based system could solve. If it's something that it cannot, then it is fine to resolve dependencies in KraftKit. [We can already parse KConfig dependencies trees](https://github.com/unikraft/kraftkit/tree/staging/kconfig) to correctly determine the order before invoking `make`. My rationale was that for those who do not use KraftKit, this issue should still be resolvable.

**Comment by mkroening** [comment]
I am not getting this error myself anymore. @nderjung, has KraftKit worked around this? Can we close this issue?

**Comment by mkroening** [comment]
As this is not an issue for me anymore, I presume this has been fixed in KraftKit.

If this is not the case feel free to reopen. :)
