### ISSUE TITLE
Add `__nonnull` keyword to appropriate function declarations

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#730]
### Feature request summary

The `__nonnull` keyword is a [macro](https://github.com/unikraft/unikraft/blob/staging/include/uk/essentials.h#L81) assigned the [`__attribute__(nonnull)` build-time attribute](https://gcc.gnu.org/onlinedocs/gcc-4.7.2/gcc/Function-Attributes.html). It's used to enforce compiler checks for arguments: it an argument is `NULL` and detected by the compiler, then a build is issued.

Add `__nonnull` keyword to all function declarations (function headers) that shouldn't receive `NULL` as their arguments.

### Related architectures

None

### Related platforms

None

### Additional context

Note that when the `__nonnull` keyword is used, a warning will be issued if there is a `NULL` check inside function bodies. Those checks will be removed, since there is already a compiler-enforced check. This is the cause of removing the `NULL` check in the `strncat()` function body in PR #546.

**Comment by AKACHI-4** [comment]
Hey @razvand Is this issue still open can I work on this

**Comment by razvand** [comment]
@AKACHI-4 , yes, the issue is available. Please start working on it.

**Comment by atharvamarathe** [comment]
I am working on this issue. Initially I will be adding the macro to the uksched library.

**Comment by vineethkm** [comment]
I have been working on this issue as well. I have added the macro to the uksglist library.
