### ISSUE TITLE
Links not working on Contributing Page

### ISSUE THREAD

**Issue by Kaushik-Iyer** [unikraft/unikraft#745]
### Describe the bug

The kind/project, kind/enhancement, and kind/bug label links do not work, and lead to 404 errors on the contributing guidelines page 

### Steps to reproduce

Clink on the above-mentioned links at https://unikraft.org/docs/contributing/#

### Expected behavior

I expected the links to lead me to the github repository I guess

**Comment by Kaushik-Iyer** [comment]
If this issue is valid, can I try to work on this as well?

**Comment by andraprs** [comment]
> If this issue is valid, can I try to work on this as well?

Thank you, @Kaushik-Iyer. Yes, sure, you can submit a PR once you develop a proposed fix.

Can you please create a similar issue in this repository instead - https://github.com/unikraft/docs - and close the current one. That is the corresponding repository for the documentation. The referenced page from the current issue is available at https://github.com/unikraft/docs/blob/main/content/en/docs/contributing/_index.md.

**Comment by andraprs** [comment]
An issue [1] was created in the docs repository. Closing the current one.

[1] https://github.com/unikraft/docs/issues/189
