### ISSUE TITLE
lib/ukboot: Critical error when running `app-helloworld` on linuxu

### ISSUE THREAD

**Issue by RaduNichita** [unikraft/unikraft#766]
### Describe the bug

When running the linuxu application for helloworld, it crashes due to a problem with memory allocator from `boot.c`

### Steps to reproduce

Run the [app-helloworld](https://github.com/unikraft/app-helloworld) application with Unikraft v0.12.

### Expected behavior

The program to dsplay the message "Hello world".

### Which architectures were you using or does this bug affect?

`linuxu`

### Which platforms were you using or does this bug affect?

`x86_64`

### Relevant log output

```shell
[ 2692.514525] Info: [libukboot] <boot.c @  245> Unikraft constructor table at 0x40f000 - 0x40f008
[ 2692.514558] Info: [libukboot] <boot.c @  264> Initialize memory allocator...
[ 2692.514571] CRIT: [libukboot] <boot.c @  268> Failed to initialize memory allocator
```

**Comment by Daparrag** [comment]
hi @RaduNichita 

I add some changes that will fix this problem.

**Comment by razvand** [comment]
**Hackathon points**: 40
