### ISSUE TITLE
nginx | weak main() called. Symbol was not replaced!

### ISSUE THREAD

**Issue by Gege-Wang** [unikraft/unikraft#767]
### Describe the bug

when I boot the nginx, I will see:
Booting from ROM..1: Set IPv4 address 172.44.0.2 mask 255.255.255.0 gw 172.44.0.1
en1: Added
en1: Interface is up
weak main() called. Symbol was not replaced!

### Steps to reproduce

make menuconfig
make
sudo qemu-system-x86_64 -fsdev local,id=myid,path=$(pwd)/fs0,security_model=none \
                        -device virtio-9p-pci,fsdev=myid,mount_tag=fs0,disable-modern=on,disable-legacy=off \
                        -netdev bridge,id=en0,br=virbr0 \
                        -device virtio-net-pci,netdev=en0 \
                        -kernel "build/app-nginx_kvm-x86_64" \
                        -append "netdev.ipv4_addr=172.44.0.2 netdev.ipv4_gw_addr=172.44.0.1 netdev.ipv4_subnet_mask=255.255.255.0 --" \
                        -cpu host \
                        -enable-kvm \
                        -nographic

### Expected behavior

[...]
0: Set IPv4 address 172.44.0.2 mask 255.255.255.0 gw 172.44.0.1
en0: Added
en0: Interface is up
[...]

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

**Comment by StefanJum** [comment]
Hi @Gege-Wang, did you select `Provide main function` from the `menuconfig` `Library options --> libnginx` screen?
If not please do that, then run a `make clean && make` and try running the app again.

**Comment by Gege-Wang** [comment]
Thank you for your comment! I have select the `Provide main function` ,but I still can see the `weak mian() called. Symbol was not replaced`.

**Comment by Gege-Wang** [comment]
Hi@SenfanJum ,Do you know why the weak main() called? I don't understand how the kraft work, In fact , I cannot use kraft to build nginx , so I must build the nginx maually

**Comment by StefanJum** [comment]
Hi @Gege-Wang, did you run `make clean` and `make` after selecting the `Provide main function` option? If so, run a `make distclean` and do the configuration and build again.
This should work with the manual build, no need for `kraft` to be used.

If you have `kraft` installed, you can also try to use the script [here](https://github.com/unikraft-upb/scripts/blob/main/musl/do-nginx) to build and run everything. You can find instructions in the repository `README` file.

**Comment by Gege-Wang** [comment]
Hi @StefanJum okok! Thank you very much!!! By the way , I wonder where the entry code for unikraft is, that is, how does the operating system compile with the application?

**Comment by StefanJum** [comment]
There is a [booting section](https://unikraft.org/docs/develop/booting/) on the [Unikraft docs website](https://unikraft.org/) :rocket: . You can find more details there. If you have more questions you can join the [Discord server](https://bit.ly/UnikraftDiscord) and we can continue to talk there.

Let me know if you get `nginx` working so we can close this issue.
