### ISSUE TITLE
Native macOS/darwin support

### ISSUE THREAD

**Issue by nderjung** [unikraft/unikraft#785]
### Feature request summary

This issue tracks enabling building Unikraft on macOS/darwin.  The changeset requires modifications to Unikraft's build system to accommodate for non-standard UNIX programs, e.g. `sed`, as well as enabling the runtime of Unikraft via QEMU on macOS.

### Related architectures

None

### Related platforms

None

**Comment by razvand** [comment]
This has been solved in #1034.
