### ISSUE TITLE
`posix-mmap` returns the `errno` value as the address and does not set `errno` in binary compatibility mode

### ISSUE THREAD

**Issue by John-Ted** [unikraft/unikraft#793]
### Describe the bug

When running a binary compatible app using [`posix-mmap`](https://github.com/unikraft/unikraft/tree/staging/lib/posix-mmap) under [`app-elfloader`](https://github.com/unikraft/app-elfloader) ,  `mmap` returns a wrong value.
The return value (memory address) is actually set to what was supposed to be the `errno`, and `errno` is not set.

### Steps to reproduce

Compile `app-elfloader` with `posix-mmap` and run a simple test app.

Example app:

```C
#include <sys/mman.h>
#include <stddef.h>
#include <fcntl.h>
#include <stdio.h>
#include <errno.h>

int main() {
        int fd1 = open("a.txt", O_RDWR);
        char *f = mmap(NULL, 4, 11111111, 444444, fd1, 0); //or the other calles mentioned below
        printf("addr=%p errno=%d\n", f, errno);
        fflush(stdout);
        munmap(f, 4);
        return 0;
}
```

### Expected behavior

For the following `mmap` calls, I expected the `app-elfloader` results to match those obtained on the host OS. For comparison, a native unikernel mostly matches the results on the hosts.
In all examples, `fd1` is a valid file descriptor.
This does not happen with the `open` call.

```
char *f = mmap(NULL, 4, 11111111, MAP_PRIVATE, fd1, 0);
Host      -> addr=0x7f9c99f38000 errno=0
Compat    -> addr=0x1000002000 errno=0
Unikernel -> addr=0x1000002000 errno=0

char *f = mmap(NULL, 4, 11111111, 444444, fd1, 0);
Host      -> addr=0xffffffffffffffff errno=22
Compat    -> addr=0x1 errno=0
Unikernel -> addr=0xffffffffffffffff errno=-1

char *f = mmap(0x1200, 4, 123123, 123123, fd1, 0);
Host      -> addr=0xffffffffffffffff errno=22
Compat    -> addr=0x1000002000 errno=0
Unikernel -> addr=0x1000002000 errno=0

char *f = mmap(NULL, 4, 0, 0, fd1, 0);
Host      -> addr=0xffffffffffffffff errno=22
Compat    -> addr=0x16 errno=0
Unikernel -> addr=0xffffffffffffffff errno=-22

char *f = mmap(NULL, 4, 432084, 31209, fd1, 0);
Host      -> addr=0xffffffffffffffff errno=22
Compat    -> addr=0x5f errno=0
Unikernel -> addr=0xffffffffffffffff errno=-95

char *f = mmap(NULL, 4, 123489312, 2930480, fd1, 0);
Host      -> addr=0xffffffffffffffff errno=1
Compat    -> addr=0x1 errno=0
Unikernel -> addr=0xffffffffffffffff errno=-1
```

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

**Comment by andraprs** [comment]
The  fix from PR https://github.com/unikraft/unikraft/pull/799 has been merged.
