### ISSUE TITLE
Problems when using the file system for write operations

### ISSUE THREAD

**Issue by LunaWhispers** [unikraft/unikraft#808]
### Describe the bug

I am using the `fwrite`API of the `lib-newlib` library to test the file writing operation.
When I write in `w` mode, I can only write up to 1KB of data.

I debugged the `sys_write` function in `lib/vfscore/syscalls.c` and found that `sys_write` can only pass in a maximum of 1KB write cache at a time, even if I want to send a larger block each time. So if I want to send a 4KB block of data, the system will call `sys_write` four times, and each time the offset value passed to the specific file system write operation is 0.
In `a` mode, in the specific file system, the offset value can be updated according to the `IO_APPEND` flag, and the data is successfully written to the end of the file.
In `w` mode. The offset is not updated every time, and the value is always 0, and each time will be written from the beginning of the file. As a result, only 1KB of data can be written at most.

### Steps to reproduce

Compile app and run a simple test app.

Example test app:
```c
#include <stdio.h>
#include <stdlib.h>

int main()
{
	int filesize = 1024*1024*100; //100MB
	int blocksize = 4096; //4KB
	char *filepath = "/test";
	
	FILE *fp = fopen(filepath, rwmode ? "wb" : "rb");
	if (fp == NULL) {
		printf("Failed to open or create file.\n");
		return -1;
	}
	
	char *buffer = (char *)malloc(blocksize);
	if (buffer == NULL) {
		printf("Failed to allocate buffer.\n");
		fclose(fp);
		return -1;
	}
	
	for (int i = 0; i < blocksize; i++) {
		buffer[i] = 'A' + i % 26;
	}
	printf("Start testing...\n");
	
	int count = 0; 
	while (count < filesize / blocksize) {
		fwrite(buffer, blocksize, 1, fp); 
		count++;
		printf("count:%d\n", count);
	}
	
	printf("Finished testing.\n");
	free(buffer); 
	fclose(fp);
	return 0;
}
```

### Expected behavior

I don't know if I misunderstood, if so, I'm very sorry.
At the same time, I have a question, why can only 1KB of data be transferred in one write operation? Wouldn't this way reduce throughput?
I would be very grateful if you could give me an answer!

**Comment by eduardvintila** [comment]
Hey, @coder-y04! 

Which version of Unikraft are you using? You mentioned running this example with `lib-newlib`; however, we have deprecated the usage of this library and we now provide full support for [`musl`](https://github.com/unikraft/lib-musl).

I have tried to reproduce the issue, but your example seems to work fine with the latest version of Unikraft and `lib-musl`. In particular, the 4KB writes are done exactly as you expect - i.e. with no overlapping happening and maximum throughput, as well.

Please let us know if we can provide further support : )

**Comment by LunaWhispers** [comment]
> Hey, @coder-y04!
> 
> Which version of Unikraft are you using? You mentioned running this example with `lib-newlib`; however, we have deprecated the usage of this library and we now provide full support for [`musl`](https://github.com/unikraft/lib-musl).
> 
> I have tried to reproduce the issue, but your example seems to work fine with the latest version of Unikraft and `lib-musl`. In particular, the 4KB writes are done exactly as you expect - i.e. with no overlapping happening and maximum throughput, as well.
> 
> Please let us know if we can provide further support : )

Hey, according to your description, I used the latest version of unikraft and musl for testing, and found that the problem I mentioned above has been perfectly solved. The problem I encountered above may be using a lower version of unikraft and newlib.
In the future, I will give up newlib and use musl for unikraft-related learning.
Thank you for your help！
