### ISSUE TITLE
Add link to Discord in `README.md`

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#835]
### Feature request summary

There is no link to [Discord](https://bit.ly/UnikraftDiscord) in the `README.md` file in the repository. Add link to make Discord more visible.

### Related architectures

None

### Related platforms

None

**Comment by gabrielmocanu** [comment]
@razvand 
There is a link if you click on the Discord badge.
![image](https://user-images.githubusercontent.com/34304856/232234266-98a8be5b-1d11-4a0a-b09f-cdd96c209c7e.png)

**Comment by ggracechoi** [comment]
Hi, my name is Grace and I'm a CS student at UT Austin. I was wondering if you could assign this issue to me?

**Comment by gabrielmocanu** [comment]
@ggracechoi  Done.

**Comment by ggracechoi** [comment]
I moved the Discord link to the very right side of the link section:

![image](https://github.com/unikraft/unikraft/assets/52022191/792505dd-d888-4215-bd53-de51a9ef2c55)

Is there a specific place you'd prefer it? Also, should I fork and push my changes?

**Comment by ggracechoi** [comment]
^ @gabrielmocanu @razvand

**Comment by razvand** [comment]
@ggracechoi , @gabrielmocanu , there is now a link for the Discord server on the [`README.md`](https://github.com/unikraft/unikraft/blob/staging/README.md), as part of the [`Join Our Discord` link](https://unikraft.org/discord). I'm closing this issue.
