### ISSUE TITLE
`virtio_ring` error when running `client` in binary compatibility mode

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#853]
### Describe the bug

When using [`app-elfloader`](https://github.com/unikraft/app-elfloader) (via the `run_app.sh` script in [`run-app-elfloader`](https://github.com/unikraft/run-app-elfloader)) to run the [`client` dynamic build](https://github.com/unikraft/dynamic-apps/tree/master/lang/c), a KVM internal error appears.

### Steps to reproduce

First start the [`server` application](https://github.com/unikraft/dynamic-apps/tree/master/lang/c) locally (native Linux run).

```console
$ ./server
````

You can easily just use the [`./do.sh`](https://github.com/unikraft-upb/scripts/tree/main/make-based/app-elfloader) script in the [`unikraft-upb/scripts` repository](https://github.com/unikraft-upb/scripts):

```console
$ ./do.sh setup
$ ./do.sh build
$ ./do.sh run client
```

### Expected behavior

There shouldn't be an error showed.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
$ sudo ./run_app.sh client
Creating bridge virbr0 if it does not exist ...
Adding IP address 172.44.0.1 to bridge virbr0 ...
Running command: 
	qemu-system-x86_64
	-m 2G
	-nographic
	-nodefaults
	-display none
	-serial stdio
	-device isa-debug-exit
	-fsdev local,security_model=passthrough,id=hvirtio0,path=../dynamic-apps/lang/c/
	-device virtio-9p-pci,fsdev=hvirtio0,mount_tag=fs0
	-kernel /media/razvan/c4f6765a-efa5-4ebd-9cf0-7da9908a0189/razvan/unikraft/scripts/workdir/apps/run-app-elfloader/../app-elfloader/build/app-elfloader_kvm-x86_64
	-initrd ../dynamic-apps/lang/c/lib64/ld-linux-x86-64.so.2
	-enable-kvm
	-cpu host
	-netdev tap,id=hnet0,vhost=off,script=/media/razvan/c4f6765a-efa5-4ebd-9cf0-7da9908a0189/razvan/unikraft/scripts/workdir/apps/run-app-elfloader/setup/up,downscript=/media/razvan/c4f6765a-efa5-4ebd-9cf0-7da9908a0189/razvan/unikraft/scripts/workdir/apps/run-app-elfloader/setup/down
	-device virtio-net-pci,netdev=hnet0,id=net0
	-append "netdev.ipv4_addr=172.44.0.2 netdev.ipv4_gw_addr=172.44.0.1 netdev.ipv4_subnet_mask=255.255.255.0
	-- /client 172.44.0.1 3333" 

1: Set IPv4 address 172.44.0.2 mask 255.255.255.0 gw 172.44.0.1
en1: Added
en1: Interface is up
Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
             Epimetheus 0.12.0~3dcb33da
[    0.153482] CRIT: [appelfloader] <brk.c @   60> Cannot handle multiple user space heaps: Not implemented!
[    0.306671] ERR:  [libkvmvirtio] <virtio_ring.c @  347> Available descriptor:0, Requested descriptor:2
Duration: 949 us
Duration: 990 us
Duration: 930 us
Duration: 909 us
[    4.192276] ERR:  [libkvmvirtio] <virtio_ring.c @  347> Available descriptor:0, Requested descriptor:2
[    4.396344] ERR:  [libkvmvirtio] <virtio_ring.c @  347> Available descriptor:0, Requested descriptor:2
[    4.459776] ERR:  [libkvmvirtio] <virtio_ring.c @  347> Available descriptor:0, Requested descriptor:2
Duration: 976 us
[    5.717009] ERR:  [libkvmvirtio] <virtio_ring.c @  347> Available descriptor:0, Requested descriptor:2
```

**Comment by mkroening** [comment]
We run into this issue when trying to use Unikraft with bigger network transfers.

I created a minimal reproduction (a very simple C server): [mkroening/unikraft-virtio_ring-error-repro](https://github.com/mkroening/unikraft-virtio_ring-error-repro).

This issue seems to be a very nasty race condition somewhere.
It depends on buffer size and a pause between socket writes.
More information can be found in the repo.

This issue makes it impossible to use Unikraft with bigger networking tasks properly.

**Comment by mkroening** [comment]
I was able to reproduce the issue in every Unikraft version down to 0.5 (0.4 does not like my network configuration arguments), so it has probably existed since forever!

Side note: The 0.4 and welcome message looks very sleek :D
```terminal
Welcome to  _ __             _____
 __ _____  (_) /__ _______ _/ _/ /_
/ // / _ \/ /  '_// __/ _ `/ _/ __/
\_,_/_//_/_/_/\_\/_/  \_,_/_/ \__/
                Rhea 0.4.0~00bbf2cf
```
