### ISSUE TITLE
app-compat: `Not a directory` error and assertion failure when running `gzip` with `app-elfloader`

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#858]
### Describe the bug

When using [`app-elfloader`](https://github.com/unikraft/app-elfloader) (via the `run_app.sh` script in [`run-app-elfloader`](https://github.com/unikraft/run-app-elfloader)) to run the [`gzip` dynamic build](https://github.com/unikraft/dynamic-apps/tree/master/gzip) and the [`gzip` static PIE build](https://github.com/unikraft/static-pie-apps/tree/master/gzip), a `Not a directory` error appears based on a `utimensat` system call.

Also, a dentry-related assertion appears. This is also part of the [`echo` dynamic build](https://github.com/unikraft/dynamic-apps/tree/master/echo) and the [`ls` dynamic build](https://github.com/unikraft/dynamic-apps/tree/master/ld).

### Steps to reproduce

You can easily just use the [`./do.sh`](https://github.com/unikraft-upb/scripts/tree/main/make-based/app-elfloader) script in the [`unikraft-upb/scripts` repository](https://github.com/unikraft-upb/scripts):

```console
$ ./do.sh setup
$ ./do.sh build
$ ./do.sh run_built gzip
$ ./do.sh run_built gzip_static
```

### Expected behavior

There shouldn't be any errors printed.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
write(fd:4, "\x1F\x8B\x08\x08gjBd\x00\x03test.txt\x00+I-.\xE1"..., 34) = 34
close(fd:3) = OK
utimensat(0x4, 0x0, ...) = Not a directory (-20)
gzip: write(fd:2, "gzip: ", 6) = 6
/test.txt.gz: Not a directory
write(fd:2, "/test.txt.gz: Not a dire"..., 30) = 30
fchown(0x4, 0x0, ...) = 0x0
fchmod(0x4, 0x1b4, ...) = 0x0
close(fd:4) = OK
rt_sigprocmask(0x0, 0x100021a600, ...) = 0x0
unlink(0x100021dd00, 0x100021a600, ...) = 0x0
rt_sigprocmask(0x2, 0x47f92f7d0, ...) = 0x0
lseek(0x0, 0x0, ...) = 0x0
close(fd:0) = OK
[    0.327286] CRIT: [libvfscore] <dentry.c @  216> Assertion failure: dp->d_refcnt > 0
```

**Comment by marcrittinghaus** [comment]
I can reproduce the assert. Looking into it...
