### ISSUE TITLE
Ruby2.5 interpreter crashes in binary compatibility mode

### ISSUE THREAD

**Issue by razvand** [unikraft/unikraft#915]
### Describe the bug

The Ruby2.5 interpreter crashes when running in binary compatibility mode via [`app-elfloader`](https://github.com/unikraft/app-elfloader).

### Steps to reproduce

Use the [`run.sh` script]() in the [`run-app-elfloader` repository]():

```console
$ ./run.sh -r ../dynamic-apps/lang/ruby/ /usr/bin/ruby2.5 -e \'puts "Hello, World!"\'
```

### Expected behavior

Running the Ruby interpreter with Unikraft should print `Hello, World!`, the same as running it natively under Linux:

```console
$ ./lang/ruby/usr/bin/ruby2.5 -e 'puts "Hello, World!"'
Hello, World!
```

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

```shell
clock_gettime(CLOCK_PROCESS_CPUTIME_ID, <out>timespec:0x4000dfb60) = Invalid argument (-22)
getrusage(0x0, 0x4000dfb60, ...) = 0x0
[    0.608894] CRIT: [libkvmplat] <traps.c @   85> Unhandled Trap 6 (invalid opcode), error code=0x0
[    0.612151] CRIT: [libkvmplat] <trace.c @   41> RIP: 0000000000000003 CS: 0008
[    0.614769] CRIT: [libkvmplat] <trace.c @   43> RSP: 00000004000dfbf8 SS: 0010 EFLAGS: 00010282
[    0.618125] CRIT: [libkvmplat] <trace.c @   45> RAX: 0000000000000000 RBX: 0000000000000000 RCX: 00000010005cac57
[    0.622086] CRIT: [libkvmplat] <trace.c @   47> RDX: ffffffffffffff80 RSI: 00000004000dfb60 RDI: 0000000000000000
[    0.625864] CRIT: [libkvmplat] <trace.c @   49> RBP: 00000004002009a0 R08: 0000000000000077 R09: 0000000000000000
[    0.629632] CRIT: [libkvmplat] <trace.c @   51> R10: 0000000400200010 R11: 0000000000000246 R12: 0000000400201480
[    0.633423] CRIT: [libkvmplat] <trace.c @   53> R13: 0000000400200c00 R14: 0000000000000000 R15: 0000000000000000
[    0.637320] CRIT: [libkvmplat] <traps.c @   90> Crashing
```

**Comment by StefanJum** [comment]
This is caused by an incompatibility in the `struct rusage` structure between the [`glibc` one](https://elixir.bootlin.com/glibc/glibc-2.31/source/resource/bits/types/struct_rusage.h#L33) and [ours](https://github.com/unikraft/unikraft/blob/staging/lib/posix-process/musl-imported/include/sys/resource.h#L26) (imported from musl). I'll be back with a PR.
